apiVersion: v1
kind: ConfigMap
metadata:
  name: secretenv
data:
  application.yml: |+
    server:
      port: 8080
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${SECRETS_USER}
      password: ${SECRETS_PASSWORD}