#!/bin/bash
kubectl create secret generic mysqlcontainer --from-literal=username=root --from-literal=password=tpm1234 
kubectl get secret  mysqlcontainer -o yaml > secret.yaml
kubectl apply -f secret.yaml
kubectl apply -f config.yaml
kubectl apply -f pod.yaml
kubectl apply -f service.yaml
kubectl apply -f client.yaml