apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: SECRETS_USER
          valueFrom:
            secretKeyRef:
              name: mysqlcontainer
              key: username
        - name: SECRETS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlcontainer
              key: password

--------------------------
apiVersion: v1
kind: Service
metadata:
  name: catalogservice
  labels:
    app: catalogservice
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: catalogservice