apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - env:
          - name: SECRETS_USER
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: username
          - name: SECRETS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: password