--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: app
  name: app
spec: 
  template: 
    metadata: 
      labels: 
        app: app
    spec: 
      containers: 
        - 
          env: ~
          image: gcr.io/qwiklabs-gcp-01f0cd088e25ac6d/app
          name: app
          ports: 
            - 
              containerPort: 8080
        - 
          name: SECRETS_USER
          valueFrom: 
            secretKeyRef: 
              key: username
              name: mysqlcontainer
        - 
          name: SECRETS_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: password
              name: mysqlcontainer
