apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice
spec:
  selector:
    matchLabels:
      app: invoice
  template:    
    metadata:
      labels:
        app: invoice
    spec:
      containers:
        - name: mysql-container
          image: gcr.io/perceptive-day-252709/mysql-container
          env:
          - name: SECRETS_USER
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: username
          - name: SECRETS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: password