apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    spec:
      containers:
        - name: invoice
          image: gcr.io/perceptive-day-252709/Spring-Boot-GCP
          imagePullPolicy: Never
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: mysql
          - name: SECRETS_USER
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: username
          - name: SECRETS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: password