apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
          - name: SECRETS_USER
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: username
          - name: SECRETS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlcontainer
                key: password
          ports:
          - containerPort: 3306
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data

      volumes:
      - name: mysql-data