--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: app-gke
  name: app-gke
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: app-gke
  template: 
    metadata: 
      labels: 
        app: app-gke
    spec: 
      containers: 
        - name: app-gke
          image: gcr.io/[PROJECT ID]/app-gke:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env:
            - name: SECRETS_USER
              valueFrom:
                secretKeyRef:
                  name: mysqlcontainer
                  key: username
            - name: SECRETS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlcontainer
                  key: password           
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy", "-instances=qwiklabs-gcp-3c9d8f314a12d81c:us-central1:mysqlcontainer=tcp:3306", "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: cloudsql-instance-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: app-gke
spec:
  selector:
    app: app-gke
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer