apiVersion: v1
kind: Pod
metadata:
  name: secretenv
spec:
  serviceAccount: mysql-container
  volumes:
  - name: secretvolume
    secret:
      secretName: mysqlcontainer
  containers:
  - name: secretcontainer
    image: redis
    env:
      - name: SECRETS_USER
        valueFrom:
          secretKeyRef:
            name: mysqlcontainer
            key: username
      - name: SECRETS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysqlcontainer
            key: password
  restartPolicy: Never