apiVersion: v1
kind: Pod
metadata:
  name: secretenv
spec:
  containers:
  - name: secretcontainer
    image: gcr.io/perceptive-day-252709/Spring-Boot-GCP
    env:
      - name: SECRETS_USER
        valueFrom:
          secretKeyRef:
            name: mysqlcontainer
            key: username
      - name: SECRETS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysqlcontainer
            key: password
  restartPolicy: Never