#set up properties
management:
    endpoint:
        restart:
            enabled: true

spring:
    data:
        rest: 
            base-path: /api
    application:
        name: Invoice-Service
    cloud:
        kubernetes:
            reload:
                enabled: true
            config:
                enableApi: true
                enabled: true
            secrets:
                name: mysqlcontainer
                enabled: true
                enableApi: true
        gcp:
            project-id: perceptive-day-252709
            credentials:
                location: classpath:key.json
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: perceptive-day-252709:us-central1:mysql-container
    datasource:
        password: ${SECRETS_PASSWORD:tpm1234}
        username: ${SECRETS_USER:root}
        schema: classpath:/schema.sql
        initialization-mode: always