#set up properties
management:
    security:
        enabled: false
    endpoint:
        restart:
            enabled: true

spring:
    data:
        rest: 
            base-path: /api
    application:
        name: invoice
    datasource:
        password: ${SECRETS_PASSWORD:tpm1234}
        username: ${SECRETS_USER:james}
        schema: classpath:/schema.sql
        initialization-mode: always